social/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/results', views.results, name='results'),
    path('<int:post_id>/vote', views.vote, name='vote')
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'))
]

social/posts/models.py
from django.db import models
from datetime import datetime
from django_mysql.models import ListCharField

# Create your models here.

class Posts(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    by = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Posts"

class Rating(models.Model): 
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)

    def __int__(self):
        return self.likes

    class Meta:
        verbose_name_plural = "Rating"

social/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Posts, Rating
from django.template import loader
from django.urls import reverse

# GET Posts and .
def index(request):
    # return HttpResponse('HELLO WORLD')
    latest_posts_list = Posts.objects.order_by('-created_at')
    context = {'latest_posts_list': latest_posts_list}

    return render(request, 'posts/index.html', context)


# Show specific post

def detail(request, post_id):
    try:
        post = Posts.objects.get(pk=post_id)
    except Posts.DoesNotExist:
        raise Http404("Post does not exist")
    return render(request, 'posts/detail.html', { 'post': post })


# Get post and display results
def results(request, post_id):
    post = get_object_or_404(Posts, pk=post_id)
    return render(request, 'posts/results.html', { 'post': post })


#  Vote for a choice
def vote(request, post_id):
    post = get_object_or_404(Posts, pk=post_id)
    # print('REQUEST:::', request.POST['like'])
    
    if( 'like' in request.POST ):
        selected_like = post.rating_set.get(pk=int(request.POST['like']))
        selected_like.likes += 1
        selected_like.save()
        print(selected_like)
    elif ('dislike' in request.POST):
        selected_dislike = post.rating_set.get(pk=int(request.POST['dislike']))
        selected_dislike.dislikes += 1
        selected_dislike.save()
        print(selected_dislike)
    return HttpResponseRedirect(reverse('posts:results', args=(post.id,)))

social/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Posts {% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

social/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'posts:index' %}" class="btn btn-seconndary btn-sm mb-3">Back to Posts</a>
<h1 class="text-senter mb-3">{{ post.title }}</h1>
<p class="mb-3">{{post.body}}</p>


{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'posts:vote' post.id %}" method="post">
    {% csrf_token %}
    {% for choice in post.rating_set.all %}
    <button type="submit" name="like" value={{choice.id}} class="btn btn-success btn-md btn-block mt-4">Like</button>
    <button type="submit" name="dislike" value={{choice.id}} class="btn btn-danger btn-md btn-block mt-4">Dislike</button>
    {% endfor %}
</form>
{% endblock %}

social/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-senter mb-3">Social Posts</h1>
    {% if latest_posts_list %}
        {% for post in latest_posts_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead card-title">{{post.title}}</p>
                    <p class="card-text">Created at: {{post.created_at}}</p>
                    <a href="{% url 'posts:detail' post.id %}" class="text-secondary" style="margin-right: 20px;">See all..</a>
                    <a href="{% url 'posts:results' post.id %}" class="text-secondary">See Rating</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No Posts availabel</p>
    {% endif %}

{% endblock %}

social/templates/posts/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ post.title }}</h1>

<ul class="list-group mb-5">
    {% for choice in post.rating_set.all %}
    <li class="list-group-item">
        Likes: {{ choice.likes }} 
        <!-- <span class="badge badge-success float-right">
            Dislikes{{ choice.dislikes }}
        </span> -->
    </li>
    <li class="list-group-item">
        Dislikes: {{ choice.dislikes }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'posts:index' %}" class="btn btn-success">Back to Posts</a>
<a href="{% url 'posts:detail' post.id %}" class="btn btn-dark">Vote again?</a>
{% endblock %}